import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Inter } from 'next/font/google'
// 또는 Geist 폰트를 사용한다면:
// import { GeistSans, GeistMono } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
// 또는:
// const geistSans = GeistSans({ subsets: ['latin'] })
// const geistMono = GeistMono({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* 또는 Geist 폰트 사용시: */}
        {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> */}
        
        <header>
          <h1>WonderChain</h1>
        </header>
        
        {children}
        
        <footer>© 2025 WonderChain</footer>
      </body>
    </html>
  );
}
